server:
  port: 8010

limit:
  time: 10
  count: 30

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 资源服务
        - id: resource-server
          uri: lb://resource-server
          predicates:
            - Path=/resource/**
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/user/**
          filters:
            - name: RequestRateLimiter #限流名称
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5 #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 5 #令牌桶总容量
        - id: post-server
          uri: lb://post-server
          predicates:
            - Path=/post/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 5
        - id: comment-server
          uri: lb://comment-server
          predicates:
            - Path=/comment/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 5
