server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 资源服务
        - id: resource-server
          uri: lb://resource-server
          predicates:
            - Path=/resource/**
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/user/**
        - id: post-server
          uri: lb://post-server
          predicates:
            - Path=/post/**